#!/bin/bash

jarsDir=$1
output=$2

sourcePath="$(dirname ${BASH_SOURCE[0]})/WebApp/src:$(dirname ${BASH_SOURCE[0]})/WebApp/junit"

# These classpath entries are taken from the WAR file generated by Eclipse
# Not all are strictly necessary, but unused ones don't do any harm
classPath="${jarsDir}/activation-1.1.1.jar"
classPath="${classPath}:${jarsDir}/aopalliance-repackaged-2.6.1.jar"
classPath="${classPath}:${jarsDir}/commons-beanutils-1.8.3.jar"
classPath="${classPath}:${jarsDir}/commons-codec-1.3.jar"
classPath="${classPath}:${jarsDir}/commons-collections-3.2.1.jar"
classPath="${classPath}:${jarsDir}/commons-csv-1.7.jar"
classPath="${classPath}:${jarsDir}/commons-digester-1.8.1.jar"
classPath="${classPath}:${jarsDir}/commons-email-1.4.jar"
classPath="${classPath}:${jarsDir}/commons-fileupload-1.3.1.jar"
classPath="${classPath}:${jarsDir}/commons-io-2.2.jar"
classPath="${classPath}:${jarsDir}/commons-lang3-3.11.jar"
classPath="${classPath}:${jarsDir}/commons-logging-1.2.jar"
classPath="${classPath}:${jarsDir}/commons-math3-3.6.jar"
classPath="${classPath}:${jarsDir}/commons-text-1.9.jar"
classPath="${classPath}:${jarsDir}/commons-validator-1.4.1.jar"
classPath="${classPath}:${jarsDir}/flyway-core-7.15.0.jar"
classPath="${classPath}:${jarsDir}/geronimo-atinject_1.0_spec-1.0.jar"
classPath="${classPath}:${jarsDir}/gson-2.10.1.jar"
classPath="${classPath}:${jarsDir}/hk2-api-2.6.1.jar"
classPath="${classPath}:${jarsDir}/hk2-locator-2.6.1.jar"
classPath="${classPath}:${jarsDir}/hk2-utils-2.6.1.jar"
classPath="${classPath}:${jarsDir}/istack-commons-runtime-4.0.0-M3.jar"
classPath="${classPath}:${jarsDir}/jakarta.activation-2.0.0-RC3.jar"
classPath="${classPath}:${jarsDir}/jakarta.annotation-api-1.3.5.jar"
classPath="${classPath}:${jarsDir}/jakarta.inject-2.6.1.jar"
classPath="${classPath}:${jarsDir}/jakarta.json-1.1.6.jar"
classPath="${classPath}:${jarsDir}/jakarta.json-api-1.1.6.jar"
classPath="${classPath}:${jarsDir}/jakarta.validation-api-2.0.2.jar"
classPath="${classPath}:${jarsDir}/jakarta.ws.rs-api-2.1.6.jar"
classPath="${classPath}:${jarsDir}/jakarta.xml.bind-api-3.0.0-RC3.jar"
classPath="${classPath}:${jarsDir}/javassist-3.25.0-GA.jar"
classPath="${classPath}:${jarsDir}/javax.activation-api-1.2.0.jar"
classPath="${classPath}:${jarsDir}/javax.annotation-api-1.3.2.jar"
classPath="${classPath}:${jarsDir}/javax.el-api-3.0.0.jar"
classPath="${classPath}:${jarsDir}/javax.mail-1.5.2.jar"
classPath="${classPath}:${jarsDir}/javax.ws.rs-api-2.1.1.jar"
classPath="${classPath}:${jarsDir}/javax.xml.soap-api-1.4.0.jar"
classPath="${classPath}:${jarsDir}/jaxb-api-2.3.1.jar"
classPath="${classPath}:${jarsDir}/jaxb-core-3.0.0-M4.jar"
classPath="${classPath}:${jarsDir}/jaxb-runtime-3.0.0-M4.jar"
classPath="${classPath}:${jarsDir}/jaxws-api-2.3.1.jar"
classPath="${classPath}:${jarsDir}/jersey-client-2.34.jar"
classPath="${classPath}:${jarsDir}/jersey-common-2.34.jar"
classPath="${classPath}:${jarsDir}/jersey-container-servlet-2.34.jar"
classPath="${classPath}:${jarsDir}/jersey-container-servlet-core-2.34.jar"
classPath="${classPath}:${jarsDir}/jersey-entity-filtering-2.34.jar"
classPath="${classPath}:${jarsDir}/jersey-hk2-2.34.jar"
classPath="${classPath}:${jarsDir}/jersey-media-moxy-2.34.jar"
classPath="${classPath}:${jarsDir}/jersey-media-multipart-2.34.jar"
classPath="${classPath}:${jarsDir}/jersey-server-2.34.jar"
classPath="${classPath}:${jarsDir}/mimepull-1.9.13.jar"
classPath="${classPath}:${jarsDir}/myfaces-api-2.2.8.jar"
classPath="${classPath}:${jarsDir}/myfaces-bundle-2.2.8.jar"
classPath="${classPath}:${jarsDir}/myfaces-impl-2.2.8.jar"
classPath="${classPath}:${jarsDir}/mysql-connector-java-8.0.29.jar"
classPath="${classPath}:${jarsDir}/org.eclipse.persistence.asm-2.7.6.jar"
classPath="${classPath}:${jarsDir}/org.eclipse.persistence.core-2.7.6.jar"
classPath="${classPath}:${jarsDir}/org.eclipse.persistence.moxy-2.7.6.jar"
classPath="${classPath}:${jarsDir}/osgi-resource-locator-1.0.3.jar"
classPath="${classPath}:${jarsDir}/primefaces-13.0.0.jar"
classPath="${classPath}:${jarsDir}/protobuf-java-3.19.4.jar"
classPath="${classPath}:${jarsDir}/simplelatlng-1.4.0.jar"
classPath="${classPath}:${jarsDir}/txw2-3.0.0-M4.jar"

# These classpath entries do not appear in the WAR file, but
# are required for javadoc
classPath="${classPath}:${jarsDir}/servlet-api.jar" # Copied from tomcat/libs

# JUnit libraries
classPath="${classPath}:${jarsDir}/flyway-spring5-test-5.2.4.jar"
classPath="${classPath}:${jarsDir}/junit-jupiter-api-5.7.0.jar"
classPath="${classPath}:${jarsDir}/junit-jupiter-params-5.7.0-all.jar"
classPath="${classPath}:${jarsDir}/apiguardian-api-1.1.0.jar"
classPath="${classPath}:${jarsDir}/mockito-core-3.5.10.jar"
classPath="${classPath}:${jarsDir}/spring-context-5.2.0.RELEASE.jar"
classPath="${classPath}:${jarsDir}/spring-test-5.2.0.RELEASE.jar"
classPath="${classPath}:${jarsDir}/spring-beans-5.2.0.RELEASE.jar"

javadoc -sourcepath "$sourcePath" -d "$output" \
        -subpackages uk.ac.exeter.QuinCe \
        -source 17 -private \
        -windowtitle "QuinCe Javadoc" -doctitle "QuinCe Javadoc" \
        -classpath "$classPath" \
        -link https://docs.oracle.com/en/java/javase/17/docs/api \
        -link https://javadoc.io/doc/org.primefaces/primefaces/13.0.0/ \
        -link https://commons.apache.org/proper/commons-email/javadocs/api-release/ \
        -link https://junit.org/junit5/docs/5.7.0/api/ \
        -link https://docs.spring.io/spring-framework/docs/current/javadoc-api/ \
        -link https://www.javadoc.io/doc/org.mockito/mockito-core/5.13.0/package-list/ \

