#!/bin/bash

jarsDir=$1
output=$2

sourcePath="$(dirname ${BASH_SOURCE[0]})/WebApp/src:$(dirname ${BASH_SOURCE[0]})/WebApp/junit"

# These classpath entries are taken from the WAR file generated by Eclipse
# Not all are strictly necessary, but unused ones don't do any harm
classPath="${jarsDir}/activation-1.1.1.jar"
classPath="${classPath}:${jarsDir}/aopalliance-repackaged-2.5.0-b42.jar"
classPath="${classPath}:${jarsDir}/commons-beanutils-1.8.3.jar"
classPath="${classPath}:${jarsDir}/commons-codec-1.3.jar"
classPath="${classPath}:${jarsDir}/commons-collections-3.2.1.jar"
classPath="${classPath}:${jarsDir}/commons-digester-1.8.1.jar"
classPath="${classPath}:${jarsDir}/commons-email-1.4.jar"
classPath="${classPath}:${jarsDir}/commons-fileupload-1.3.1.jar"
classPath="${classPath}:${jarsDir}/commons-io-2.2.jar"
classPath="${classPath}:${jarsDir}/commons-lang3-3.4.jar"
classPath="${classPath}:${jarsDir}/commons-logging-1.2.jar"
classPath="${classPath}:${jarsDir}/commons-math3-3.6.jar"
classPath="${classPath}:${jarsDir}/commons-validator-1.4.1.jar"
classPath="${classPath}:${jarsDir}/cupertino-1.0.10.jar"
classPath="${classPath}:${jarsDir}/geronimo-atinject_1.0_spec-1.0.jar"
classPath="${classPath}:${jarsDir}/gson-2.8.5.jar"
classPath="${classPath}:${jarsDir}/hk2-api-2.5.0-b42.jar"
classPath="${classPath}:${jarsDir}/hk2-locator-2.5.0-b42.jar"
classPath="${classPath}:${jarsDir}/hk2-utils-2.5.0-b42.jar"
classPath="${classPath}:${jarsDir}/javassist-3.22.0-CR2.jar"
classPath="${classPath}:${jarsDir}/javax.annotation-api-1.2.jar"
classPath="${classPath}:${jarsDir}/javax.el-api-3.0.0.jar"
classPath="${classPath}:${jarsDir}/javax.inject-1.jar"
classPath="${classPath}:${jarsDir}/javax.inject-2.5.0-b42.jar"
classPath="${classPath}:${jarsDir}/javax.json-1.0.4.jar"
classPath="${classPath}:${jarsDir}/javax.mail-1.5.2.jar"
classPath="${classPath}:${jarsDir}/javax.ws.rs-api-2.1.jar"
classPath="${classPath}:${jarsDir}/jersey-client-2.27.jar"
classPath="${classPath}:${jarsDir}/jersey-common-2.27.jar"
classPath="${classPath}:${jarsDir}/jersey-container-servlet-2.27.jar"
classPath="${classPath}:${jarsDir}/jersey-container-servlet-core-2.27.jar"
classPath="${classPath}:${jarsDir}/jersey-entity-filtering-2.27.jar"
classPath="${classPath}:${jarsDir}/jersey-hk2-2.27.jar"
classPath="${classPath}:${jarsDir}/jersey-media-jaxb-2.27.jar"
classPath="${classPath}:${jarsDir}/jersey-media-moxy-2.27.jar"
classPath="${classPath}:${jarsDir}/jersey-media-multipart-2.27.jar"
classPath="${classPath}:${jarsDir}/jersey-server-2.27.jar"
classPath="${classPath}:${jarsDir}/joda-time-2.7.jar"
classPath="${classPath}:${jarsDir}/mimepull-1.9.6.jar"
classPath="${classPath}:${jarsDir}/myfaces-api-2.2.8.jar"
classPath="${classPath}:${jarsDir}/myfaces-bundle-2.2.8.jar"
classPath="${classPath}:${jarsDir}/myfaces-impl-2.2.8.jar"
classPath="${classPath}:${jarsDir}/mysql-connector-java-5.1.36.jar"
classPath="${classPath}:${jarsDir}/org.eclipse.persistence.asm-2.6.4.jar"
classPath="${classPath}:${jarsDir}/org.eclipse.persistence.core-2.6.4.jar"
classPath="${classPath}:${jarsDir}/org.eclipse.persistence.moxy-2.6.4.jar"
classPath="${classPath}:${jarsDir}/osgi-resource-locator-1.0.1.jar"
classPath="${classPath}:${jarsDir}/primefaces-6.2.jar"
classPath="${classPath}:${jarsDir}/validation-api-1.1.0.Final.jar"

# These classpath entries do not appear in the WAR file, but
# are required for javadoc
classPath="${classPath}:${jarsDir}/servlet-api.jar" # Copied from tomcat/libs

# JUnit libraries
classPath="${classPath}:${jarsDir}/flyway-spring5-test-5.2.1.jar"
classPath="${classPath}:${jarsDir}/junit-jupiter-api-5.5.2.jar"
classPath="${classPath}:${jarsDir}/junit-jupiter-params-5.0.0.jar"
classPath="${classPath}:${jarsDir}/mockito-all-1.10.19.jar"
classPath="${classPath}:${jarsDir}/org.springframework.context.jar"
classPath="${classPath}:${jarsDir}/spring-beans-5.1.0.RELEASE.jar"
classPath="${classPath}:${jarsDir}/spring-test-5.1.0.RELEASE.jar"


javadoc -sourcepath "$sourcePath" -d "$output" \
        -subpackages uk.ac.exeter.QuinCe:junit.uk.ac.exeter.QuinCe \
        -source 1.8 -private \
        -windowtitle "QuinCe Javadoc" -doctitle "QuinCe Javadoc" \
        -classpath "$classPath" \
        -link https://docs.oracle.com/javase/8/docs/api/ \
        -link https://docs.oracle.com/javaee/7/api/ \
        -link http://www.joda.org/joda-time/apidocs/ \
        -link http://www.primefaces.org/docs/api/6.1/ \
        -link https://commons.apache.org/proper/commons-email/javadocs/api-release/ \
        -link https://junit.org/junit5/docs/current/api/ \
        -link https://docs.spring.io/spring-framework/docs/current/javadoc-api/ \
        -link https://static.javadoc.io/org.mockito/mockito-core/2.15.0/ \

