[output]

  # The column headers for the output file
  # To join two fields add a tilde sign (~) between the names
  columns = [
    "Timestamp",
    "Measurement type",
    "Zero A/D",
    "Current A/D",
    "CO2",
    "IRGA temperature",
    "Humidity",
    "Humidity sensor temperature",
    "Cell gas pressure",
    "IRGA detector temperature",
    "IRGA source temperature",
    "Pro Oceanus voltage",
    "SST",
    "Salinity",
    "Sound Velocity",
    "Specific Conductivity",
    "Conductivity",
    "Pressure (depth)",
    "Oxygen",
    "Battery Voltage",
    "Wind Direction",
    "Wind Speed",
    "Air Temperature",
    "Atmospheric Pressure",
    "Air Humidity",
    "Latitude",
    "Longitude"
  ]

  # Timestamp column.
  timestamp_column = "Timestamp"

  # Value to store in empty columns
  empty_col_value = "NaN"

[input]
  [[input.tables]]
    name = "co2atm"

    fixed_values = [
      ["Measurement type", "A M"]
    ]

    # Outfield = Infield
    mapping = [
      ["Timestamp", "TimeStamp"],
      ["Zero A/D", "Zero_AD"],
      ["Current A/D", "Current_AD"],
      ["CO2", "CO2_Avg"],
      ["IRGA temperature", "IRGAavgTemp_Avg"],
      ["Humidity", "Humidity_Avg"],
      ["Humidity sensor temperature", "HumidTemp_Avg"],
      ["Cell gas pressure", "GasStrPressure_Avg"],
      ["Pro Oceanus voltage", "SupplyVoltage_Avg"]
    ]

    timestamp_format = "%Y-%m-%d %H:%M:%S"

  [[input.tables]]
    name = "co2water"

    fixed_values = [
      ["Measurement type", "W M"]
    ]

    # Outfield = Infield
    mapping = [
      ["Timestamp", "TimeStamp"],
      ["Zero A/D", "Zero_AD"],
      ["Current A/D", "Current_AD"],
      ["CO2", "CO2_Avg"],
      ["IRGA temperature", "IRGAavgTemp_Avg"],
      ["Humidity", "Humidity_Avg"],
      ["Humidity sensor temperature", "HumidTemp_Avg"],
      ["Cell gas pressure", "GasStrPressure_Avg"],
      ["Pro Oceanus voltage", "SupplyVoltage_Avg"]
    ]

    timestamp_format = "%Y-%m-%d %H:%M:%S"

  [[input.tables]]
    name = "sbe37"

    mapping = [
      ["Timestamp", "TimeStamp"],
      ["SST", "temperature"],
      ["Conductivity", "conductivity"],
      ["Pressure (depth)", "pressure"],
      ["Oxygen", "oxygen"],
      ["Salinity", "salinity"],
      ["Sound Velocity", "soundvelo"],
      ["Specific Conductivity", "specificcond"]
    ]

    timestamp_format = "%Y-%m-%d %H:%M:%S"

  [[input.tables]]
    name = "victron"

    mapping = [
      ["Timestamp", "timestamp"],
      ["Battery Voltage", "battv"]
    ]

    timestamp_format = "%Y-%m-%dT%H:%M:%S.%fZ"

  [[input.tables]]
    name = "meteo"

    mapping = [
      ["Timestamp", "timestamp"],
      ["Wind Direction", "winddirection"],
      ["Wind Speed", "windspeed"],
      ["Air Temperature", "temperature"],
      ["Atmospheric Pressure", "pressure"],
      ["Air Humidity", "humidity"],
      ["Latitude", "latitude"],
      ["Longitude", "longitude"]
    ]

    timestamp_format = "%Y-%m-%d %H:%M:%S"

