flowchart TB

  subgraph l2[L2]
    l2_1[Jul 2]
    l2_2[Jul 3]
    l2_1~~~l2_2
  end

  subgraph nrt3[NRT v3]
    nrt3_4[Jul 4]
  end

  subgraph nrt2[L1 v2]
    nrt2_1[Jul 1]
    nrt2_2[Jul 2]
    nrt2_3[Jul 3]
    nrt2_4[Jul 4]
    nrt2_1~~~nrt2_2
    nrt2_2~~~nrt2_3
    nrt2_3~~~nrt2_4
  end

  l2-->|partialUpload +<br/>isNextVersionOf|nrt2
  nrt3-->|partialUpload +<br/>isNextVersionOf|nrt2

  subgraph nrt1[L1 v1]
    nrt1_1[Jul 1]
    nrt1_2[Jul 2]
    nrt1_3[Jul 3]
    nrt1_1~~~nrt1_2
    nrt1_2~~~nrt1_3
  end

  nrt2-->|isNextVersionOf|nrt1

  style l2 fill:#b7ddf1,stroke:#0686B5


