name: junit

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Run CalculationCoefficientsBean multiple edit tests
      run: ./gradlew calculationCoefficientsBeanEditTest calculationCoefficientsBeanEditTestReport
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./build/reports/jacoco/report.xml
        flags: unittests
